const $=id=>document.getElementById(id);let settings={};const tabs=[...document.querySelectorAll(".tabs button")];tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id==="tab-"+b.dataset.tab));});$("close").onclick=()=>window.close();const defaults={characterBehavior:{breathing:true,blinking:true,expressions:true,speechFace:true,idle:true,walking:true,dancing:true,greeting:true,events:true,random:true,frequency:"normal",eventCooldownSec:30,autonomousMovement:true,idleThoughts:true,sleep:true,eyeTracking:true,sleepAfterMin:20,renderWakeMs:1200}};const behaviorSettings=()=>({...defaults.characterBehavior,...(settings.characterBehavior||{})});const permissionDefaults={files:"allow",applications:"allow",system:"allow",network:"allow",screen:"allow",mouseKeyboard:"allow",microphone:"allow",tasksMemory:"allow",credentials:"allow",destructive:"allow"};const permissionSettings=()=>({...permissionDefaults,...(settings.permissions||{})});
function fill(){const s=settings||{},b=behaviorSettings();$("provider").value=s.provider||"openai";$("model").value=s.model||"gpt-5";$("baseUrl").value=s.baseUrl||"";$("micMode").value=s.micMode==="on"?"on":"off";$("micPath").value=s.micPath==="whisper"?"whisper":"realtime";$("realtimeEnabled").value=s.realtimeEnabled===false?"off":"on";$("sttProvider").value=s.sttProvider||"whisper";$("sttModel").value=s.sttModel||"";$("sttLanguage").value=s.sttLanguage||"auto";$("ttsProvider").value=s.ttsProvider||"local";$("ttsModel").value=s.ttsModel||"";$("ttsVoice").value=s.ttsVoice||"";$("realtimeProvider").value=s.realtimeProvider||"openai";$("realtimeModel").value=s.realtimeModel||"gpt-realtime-2.1";$("realtimeVoice").value=s.realtimeVoice||"marin";$("brainMode").value=["api","local","auto"].includes(s.brainMode)?s.brainMode:"auto";$("maxSteps").value=Math.max(1,Math.min(100,Number(s.maxSteps)||16));$("behaviorBreathing").checked=!!b.breathing;$("behaviorBlinking").checked=!!b.blinking;$("behaviorExpressions").checked=!!b.expressions;$("behaviorSpeechFace").checked=!!b.speechFace;$("behaviorIdle").checked=!!b.idle;$("behaviorWalking").checked=!!b.walking;$("behaviorDancing").checked=!!b.dancing;$("behaviorGreeting").checked=!!b.greeting;$("behaviorEvents").checked=!!b.events;$("behaviorRandom").checked=!!b.random;$("behaviorAutonomousMovement").checked=b.autonomousMovement!==false;$("behaviorIdleThoughts").checked=b.idleThoughts!==false;$("behaviorSleep").checked=b.sleep!==false;$("behaviorEyeTracking").checked=b.eyeTracking!==false;$("behaviorFrequency").value=b.frequency;$("behaviorCooldown").value=b.eventCooldownSec;$("behaviorSleepAfterMin").value=Number(b.sleepAfterMin||20);$("behaviorRenderWakeMs").value=Number(b.renderWakeMs||1200);$("apiKey").placeholder=s.hasApiKey?"Saved securely — leave blank to keep it":"Enter API key";$("sttKey").placeholder=s.hasSttApiKey?"Saved securely — leave blank to keep it":"Enter STT API key";$("ttsKey").placeholder=s.hasTtsApiKey?"Saved securely — leave blank to keep it":"Enter TTS API key";$("realtimeKey").placeholder=s.hasRealtimeApiKey?"Saved securely — leave blank to keep it":"Enter Realtime API key";$("voiceRouting").value=s.voiceRouting||"controller";$("micSpeechRms").value=Number(s.micSpeechRms||0.09);$("micInterruptRms").value=Number(s.micInterruptRms||0.09)}
async function load(){settings=await window.saeed.getSettings()||{};fill();const p=permissionSettings();for(const id of Object.keys(permissionDefaults)){const el=$("permission-"+id);if(el)el.value=p[id]}await refreshHistory();await refreshSystem();refreshPermissionSummary()}async function save(p,button){try{settings=await window.saeed.setSettings({...settings,...p});fill();button.textContent="Saved";setTimeout(()=>button.textContent="Save",1200)}catch(e){alert(e.message)}}$("saveApi").onclick=()=>{const k=$("apiKey").value.trim();save({provider:$("provider").value,model:$("model").value,baseUrl:$("baseUrl").value,...(k?{apiKey:k}:{})},$("saveApi"))};$("saveVoice").onclick=()=>{const voiceRouting=$("voiceRouting").value;const p={micMode:$("micMode").value,micPath:$("micPath").value,realtimeEnabled:$("realtimeEnabled").value==="on",sttProvider:$("sttProvider").value,sttModel:$("sttModel").value.trim(),sttLanguage:$("sttLanguage").value.trim()||"auto",ttsProvider:$("ttsProvider").value,ttsModel:$("ttsModel").value.trim(),ttsVoice:$("ttsVoice").value.trim(),realtimeProvider:$("realtimeProvider").value,realtimeModel:$("realtimeModel").value.trim()||"gpt-realtime-2.1",realtimeVoice:$("realtimeVoice").value.trim()||"marin",voiceRouting,micSpeechRms:Math.max(0.005,Math.min(0.5,Number($("micSpeechRms").value)||0.09)),micInterruptRms:Math.max(0.005,Math.min(0.5,Number($("micInterruptRms").value)||0.09))};const a=$("sttKey").value.trim(),b=$("ttsKey").value.trim(),c=$("realtimeKey").value.trim();if(a)p.sttApiKey=a;if(b)p.ttsApiKey=b;if(c)p.realtimeApiKey=c;save(p,$("saveVoice"))};$("saveCharacter").onclick=()=>{const b={breathing:$("behaviorBreathing").checked,blinking:$("behaviorBlinking").checked,expressions:$("behaviorExpressions").checked,speechFace:$("behaviorSpeechFace").checked,idle:$("behaviorIdle").checked,walking:$("behaviorWalking").checked,dancing:$("behaviorDancing").checked,greeting:$("behaviorGreeting").checked,events:$("behaviorEvents").checked,random:$("behaviorRandom").checked,autonomousMovement:$("behaviorAutonomousMovement").checked,idleThoughts:$("behaviorIdleThoughts").checked,sleep:$("behaviorSleep").checked,eyeTracking:$("behaviorEyeTracking").checked,frequency:$("behaviorFrequency").value,eventCooldownSec:Math.max(5,Math.min(300,Number($("behaviorCooldown").value)||30)),sleepAfterMin:Math.max(1,Math.min(240,Number($("behaviorSleepAfterMin").value)||20)),renderWakeMs:Math.max(80,Math.min(5000,Number($("behaviorRenderWakeMs").value)||1200))};save({characterBehavior:b},$("saveCharacter"))};function refreshPermissionSummary(){
 const vals=Object.keys(permissionDefaults).map(id=>$("permission-"+id)?.value).filter(Boolean);
 $("permissionAllowCount").textContent=vals.filter(v=>v==="allow").length;
 $("permissionAskCount").textContent=vals.filter(v=>v==="ask").length;
 $("permissionDenyCount").textContent=vals.filter(v=>v==="deny").length;
}
function setAllPermissions(value){for(const id of Object.keys(permissionDefaults)){const el=$("permission-"+id);if(el)el.value=value}refreshPermissionSummary()}
$("allowAllPermissions").onclick=()=>setAllPermissions("allow");
$("denyAllPermissions").onclick=()=>setAllPermissions("deny");
$("askAllPermissions").onclick=()=>setAllPermissions("ask");
for(const id of Object.keys(permissionDefaults))$("permission-"+id)?.addEventListener("change",refreshPermissionSummary);
$("savePermissions").onclick=()=>save({permissions:Object.fromEntries(Object.keys(permissionDefaults).map(id=>[id,$("permission-"+id).value]))},$("savePermissions"));$("saveAgent").onclick=()=>save({brainMode:$("brainMode").value,maxSteps:Math.max(1,Math.min(100,Number($("maxSteps").value)||32))},$("saveAgent"));async function refreshHistory(){try{const h=await window.saeed.getHistory();$("historyCount").textContent=Array.isArray(h)?h.length:0}catch(e){$("historyCount").textContent="?"}}$("refreshHistory").onclick=refreshHistory;async function refreshSystem(){try{const x=await window.saeed.getCpuMetrics();$("systemInfo").textContent=x?.detail||"System metrics unavailable"}catch(e){$("systemInfo").textContent=e.message}}$("refreshSystem").onclick=refreshSystem;load();$("sttProvider")?.addEventListener("change",()=>{$("micPath").value="whisper";$("realtimeEnabled").value="off"});$("realtimeEnabled")?.addEventListener("change",()=>{$("micPath").value=$("realtimeEnabled").value==="on"?"realtime":"whisper"});$("clearAllApis").onclick=async()=>{if(!confirm("Clear all stored API keys and disable Realtime?"))return;try{settings=await window.saeed.clearAllApis();fill();$("voiceState").textContent="All API keys cleared. Realtime disabled.";}catch(e){alert(e.message)}};
async function refreshResources(){try{const x=await window.saeed.getResourceSnapshot();const p=x?.process||{},t=p.saeedTotal||{};$("resourceCpu").textContent=(t.cpuPercent??"—")+"%";$("resourceRam").textContent=(t.workingSetMB??"—")+" MB";$("resourcePrivate").textContent=(t.privateMB??"—")+" MB";$("resourceProcesses").textContent=t.processCount??"—";const rows=(p.processes||[]).slice().sort((a,b)=>Number(b.cpuPercent||0)-Number(a.cpuPercent||0));$("resourceTable").innerHTML=rows.length?'<div class="processHead"><span>Process</span><span>CPU</span><span>Working Set</span><span>Private</span></div>'+rows.map(r=>'<div class="processRow"><span>'+String(r.name||"unknown")+' <small>PID '+String(r.pid||"")+'</small></span><span>'+Number(r.cpuPercent||0).toFixed(1)+'%</span><span>'+Number(r.workingSetMB||0).toFixed(1)+' MB</span><span>'+Number(r.privateMB||0).toFixed(1)+' MB</span></div>').join(""):'No process metrics available'}catch(e){$("resourceTable").textContent=e.message}}
async function refreshDiagnostics(){try{const x=await window.saeed.getDiagnosticSnapshot();const s=x?.state||{};const items=[["Mic",s.mic],["Brain API",s.brainApi],["Local Brain",s.brainLocal],["STT / Whisper",s.stt],["TTS",s.tts],["GLB",s.glb],["CPU",s.cpu],["3D",s.threeD?.overall]];$("diagnosticGrid").innerHTML=items.map(([n,v])=>'<div class="diagCard"><b>'+n+'</b><strong class="'+String(v?.state||"unknown")+'">'+String(v?.state||"unknown").toUpperCase()+'</strong><small>'+String(v?.detail||"")+'</small></div>').join("")}catch(e){$("diagnosticGrid").textContent=e.message}}
let resourceTimer=null;
tabs.forEach(b=>b.addEventListener("click",()=>{if(b.dataset.tab==="resources"){refreshResources();clearInterval(resourceTimer);resourceTimer=setInterval(refreshResources,1000)}else{clearInterval(resourceTimer);resourceTimer=null}if(b.dataset.tab==="diagnostics")refreshDiagnostics()}));
$("refreshDiagnostics").onclick=refreshDiagnostics;
