const $=id=>document.getElementById(id);let settings={};let active="ai";let draft={};let updateInfo=null;let updating=false;
function showTab(t){active=t;document.querySelectorAll("#tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));document.querySelectorAll("[data-panel]").forEach(p=>p.classList.toggle("hidden",p.dataset.panel!==t))}
document.querySelectorAll("#tabs button").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function fill(s){settings=s||{};draft={...settings,permissions:{...(settings.permissions||{})}};$("brainMode").value=s.brainMode||"auto";$("provider").value=s.provider||"openai";$("model").value=s.model||"gpt-4o-mini";$("baseUrl").value=s.baseUrl||"https://api.openai.com/v1";$("sttProvider").value=s.sttProvider||"local";$("sttModel").value=s.sttModel||"whisper-1";$("realtimeModel").value=s.realtimeModel||"gpt-realtime-2.1";$("realtimeVoice").value=s.realtimeVoice||"marin";$("ttsProvider").value=s.ttsProvider||"local";$("ttsModel").value=s.ttsModel||"gpt-4o-mini-tts";$("ttsVoice").value=s.ttsVoice||"alloy";$("showSpeechText").checked=s.showSpeechText===true;$("speakResponses").checked=s.speakResponses!==false;$("language").value=s.language||"en";$("startWithWindows").value=String(s.startWithWindows!==false);$("characterSize").value=s.characterSize||"medium";$("characterFile").textContent=s.characterPath||"Default Saeed character";$("minimizeToTray").value=String(s.minimizeToTray!==false);renderMode(s.micMode||"off");document.querySelectorAll("[data-permission]").forEach(e=>e.value=(s.permissions||{})[e.dataset.permission]||"allow")}
function renderMode(m){document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));draft.micMode=m}
function collect(){const p={brainMode:$("brainMode").value,provider:$("provider").value,model:$("model").value,baseUrl:$("baseUrl").value,sttProvider:$("sttProvider").value,sttModel:$("sttModel").value,realtimeModel:$("realtimeModel").value,realtimeVoice:$("realtimeVoice").value,ttsProvider:$("ttsProvider").value,ttsModel:$("ttsModel").value,ttsVoice:$("ttsVoice").value,showSpeechText:$("showSpeechText").checked,speakResponses:$("speakResponses").checked,language:$("language").value,startWithWindows:$("startWithWindows").value==="true",minimizeToTray:$("minimizeToTray").value==="true",characterSize:$("characterSize").value,micMode:draft.micMode||"off",alwaysListening:(draft.micMode||"off")==="always",permissions:{}};const key=$("key").value.trim();if(key){p.apiKey=key;delete draft.clearLlmKey}const sk=$("sttKey").value.trim();if(sk)p.sttApiKey=sk;const tk=$("ttsKey").value.trim();if(tk)p.ttsApiKey=tk;const rk=$("realtimeKey").value.trim();if(rk)p.realtimeApiKey=rk;document.querySelectorAll("[data-permission]").forEach(e=>p.permissions[e.dataset.permission]=e.value);if(draft.clearLlmKey)p.clearLlmKey=true;p.email=emailDraft();p.emailEnabled=Boolean(p.email.incoming.host&&p.email.incoming.user);return p}
async function apply(closeAfter){try{const p=collect();await window.saeed.setSettings(p);settings=await window.saeed.getSettings();draft={...settings,permissions:{...(settings.permissions||{})}};$("status").textContent=closeAfter?"Saved":"Applied";if(closeAfter)setTimeout(()=>window.saeed.closeSettings?.(),150)}catch(e){$("status").textContent="Save failed: "+e.message}}
$("apply").onclick=()=>apply(false);$("ok").onclick=()=>apply(true);$("cancel").onclick=()=>window.saeed.closeSettings?.();$("close").onclick=()=>window.saeed.closeSettings?.();
$("provider").onchange=()=>$("baseRow").classList.toggle("hidden",$("provider").value!=="openai-compatible");
$("clearKey").onclick=()=>{draft.clearLlmKey=true;$("key").value="";$("status").textContent="LLM key will be cleared when you Apply or press OK"};$("clearAll").onclick=()=>{draft.clearLlmKey=true;draft.clearAllApiKeys=true;$("key").value="";$("sttKey").value="";$("realtimeKey").value="";$("status").textContent="API keys will be cleared when you Apply or press OK"};
function emailDraft(){return {enabled:true,incoming:{protocol:$("emailProtocol").value,host:$("emailInHost").value.trim(),port:Number($("emailInPort").value||993),secure:$("emailInSecure").value==="true",user:$("emailInUser").value.trim(),password:$("emailInPass").value.startsWith("•")?"":$("emailInPass").value,mailbox:$("emailMailbox").value.trim()||"INBOX"},smtp:{host:$("smtpHost").value.trim(),port:Number($("smtpPort").value||465),secure:$("smtpSecure").value==="true",user:$("smtpUser").value.trim(),password:$("smtpPass").value.startsWith("•")?"":$("smtpPass").value}}}
function fillEmail(s){const e=s.email||{},i=e.incoming||{},o=e.smtp||{};$("emailProtocol").value=i.protocol||"imap";$("emailInHost").value=i.host||"";$("emailInPort").value=i.port||993;$("emailInSecure").value=String(i.secure!==false);$("emailInUser").value=i.user||"";$("emailInPass").value=s.hasEmailIncomingPassword?"••••••••":"";$("emailMailbox").value=i.mailbox||"INBOX";$("smtpHost").value=o.host||"";$("smtpPort").value=o.port||465;$("smtpSecure").value=String(o.secure!==false);$("smtpUser").value=o.user||"";$("smtpPass").value=""}
function bytes(n){if(!Number.isFinite(Number(n))||Number(n)<=0)return "Unknown size";let x=Number(n),i=0,u=["B","KB","MB","GB"];while(x>=1024&&i<u.length-1){x/=1024;i++}return x.toFixed(i?1:0)+" "+u[i]}
function showUpdate(info){updateInfo=info;$("updateCard").classList.remove("hidden");$("updateTitle").textContent=info.newer?"Saeed AI update available: v"+info.latestVersion:"Saeed AI is up to date";$("updateMeta").textContent="Current: v"+info.currentVersion+" • "+(info.newer?"New: v"+info.latestVersion+" • Size: "+bytes(info.size):"Latest: v"+info.latestVersion);$("updateNotes").textContent=info.newer?(info.notes||"No release notes were provided."):"No update is required.";$("updateNow").classList.toggle("hidden",!info.newer||!info.assetUrl);$("updateLater").classList.toggle("hidden",!info.newer||updating);$("updateProgress").style.width="0%";$("updateProgressText").textContent="";$("updateStatus").textContent=info.newer?"A new version is ready to install.":"You already have the latest version."}
$("checkUpdates").onclick=async()=>{$("updateStatus").textContent="Checking for updates…";try{showUpdate(await window.saeed.checkForUpdates())}catch(e){$("updateStatus").textContent="Update check failed: "+e.message}};
$("updateLater").onclick=()=>{$("updateCard").classList.add("hidden");updateInfo=null};
$("updateNow").onclick=async()=>{if(!updateInfo||updating)return;updating=true;$("updateNow").disabled=true;$("updateLater").disabled=true;$("updateProgressText").textContent="Starting download…";try{await window.saeed.installUpdate(updateInfo)}catch(e){updating=false;$("updateNow").disabled=false;$("updateLater").disabled=false}};
window.saeed.onUpdateProgress?.(p=>{const total=Number(p.total||updateInfo?.size||0),done=Number(p.downloaded||0),pct=total?Math.min(100,done/total*100):0;$("updateProgress").style.width=pct+"%";$("updateProgressText").textContent="Downloading: "+bytes(done)+" / "+bytes(total)+" ("+Math.round(pct)+"%)"});
window.saeed.onUpdateStatus?.(s=>{$("updateStatus").textContent=s.text||"";if(s.state==="verifying")$("updateProgressText").textContent="Download complete. Verifying installer…";if(s.state==="installing")$("updateProgressText").textContent=s.text||"Installing…";if(s.state==="error"){updating=false;$("updateNow").disabled=false;$("updateLater").disabled=false}});
(async()=>{try{fill(await window.saeed.getSettings())}catch(e){$("status").textContent=e.message}})();
$("chooseCharacter").onclick=async()=>{try{const r=await window.saeed.selectCharacter();if(r){$("characterFile").textContent=r.path;settings.characterPath=r.path;draft.characterPath=r.path;$("status").textContent="Character selected. Apply to load it."}}catch(e){$("status").textContent="Character selection failed: "+e.message}};
$("emailApply").onclick=async()=>{try{await apply(false);$("emailStatus").textContent="Email settings saved and connection started."}catch(e){$("emailStatus").textContent=e.message}};
$("emailCheck").onclick=async()=>{try{const r=await window.saeed.checkEmail();$("emailStatus").textContent=r.ok?("Mail checked: "+(r.count||0)+" unread/new messages."):"Email error: "+(r.error||"Unknown error")}catch(e){$("emailStatus").textContent=e.message}};
$("emailSignout").onclick=async()=>{await window.saeed.signoutEmail();$("emailStatus").textContent="Signed out. Saeed is no longer connected to this mailbox."};
(async()=>{try{fillEmail(await window.saeed.getSettings())}catch{}})();
