const stateEl=document.getElementById("state"),summary=document.getElementById("summary"),current=document.getElementById("current"),available=document.getElementById("available"),bar=document.getElementById("bar"),progressText=document.getElementById("progressText"),notes=document.getElementById("notes"),install=document.getElementById("install"),later=document.getElementById("later");
const setState=(state,message)=>{stateEl.textContent=String(state||"idle");summary.textContent=message||({checking:"Checking for a new version…",available:"A new version is available.",downloading:"Downloading the update…",downloaded:"Update downloaded and ready to install.",latest:"Saeed is up to date.",error:"The update process encountered an error."}[state]||"Update status ready.");};
const setInfo=info=>{if(!info)return;available.textContent=info.version||"—";if(info.releaseNotes)notes.textContent=typeof info.releaseNotes==="string"?info.releaseNotes:JSON.stringify(info.releaseNotes,null,2)};
window.saeed.onUpdateState?.((state,message)=>setState(state,message));
window.saeed.onUpdateAvailable?.(info=>{setInfo(info);setState("available");});
window.saeed.onUpdateProgress?.(info=>{bar.style.width=Math.max(0,Math.min(100,Number(info?.percent)||0))+"%";progressText.textContent=(Number(info?.percent)||0).toFixed(0)+"% downloaded";setState("downloading");});
window.saeed.onUpdateDownloaded?.(info=>{setInfo(info);bar.style.width="100%";progressText.textContent="100% downloaded";install.disabled=false;setState("downloaded");});
window.saeed.getUpdateSnapshot?.().then(s=>{current.textContent=s?.currentVersion||"—";setInfo(s?.info);setState(s?.state||"idle");}).catch(()=>{});
install.addEventListener("click",async()=>{install.disabled=true;setState("installing","Installing the update and restarting Saeed…");await window.saeed.installUpdate?.();});
later.addEventListener("click",()=>window.close());
